// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BiosoftPlusFaceScanAPI.Models;

public partial class AppDb : DbContext
{
    public AppDb(DbContextOptions<AppDb> options)
        : base(options)
    {
    }

    public virtual DbSet<EmployeeScanTimeView> EmployeeScanTimeViews { get; set; }

    public virtual DbSet<Facescanregister> Facescanregisters { get; set; }

    public virtual DbSet<Tempimport> Tempimports { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<EmployeeScanTimeView>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("EmployeeScanTimeVIEW");

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .UseCollation("Thai_BIN");
            entity.Property(e => e.Comid)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .UseCollation("Thai_BIN")
                .HasColumnName("COMID");
            entity.Property(e => e.Employee2)
                .HasMaxLength(30)
                .IsUnicode(false)
                .UseCollation("Thai_BIN");
            entity.Property(e => e.Employee3)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Lastname1)
                .HasMaxLength(100)
                .IsUnicode(false)
                .UseCollation("Thai_BIN");
            entity.Property(e => e.Lastname2)
                .HasMaxLength(100)
                .IsUnicode(false)
                .UseCollation("Thai_BIN");
            entity.Property(e => e.Name1)
                .HasMaxLength(100)
                .IsUnicode(false)
                .UseCollation("Thai_BIN");
            entity.Property(e => e.Name2)
                .HasMaxLength(100)
                .IsUnicode(false)
                .UseCollation("Thai_BIN");
            entity.Property(e => e.TitleEng)
                .HasMaxLength(30)
                .IsUnicode(false)
                .UseCollation("Thai_BIN");
            entity.Property(e => e.TitleThai)
                .HasMaxLength(30)
                .IsUnicode(false)
                .UseCollation("Thai_BIN");
        });

        modelBuilder.Entity<Facescanregister>(entity =>
        {
            entity.ToTable("FACESCANREGISTER");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Floors)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("floors");
            entity.Property(e => e.Live).HasColumnName("live");
            entity.Property(e => e.Mac)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("mac");
            entity.Property(e => e.Modelname)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("modelname");
            entity.Property(e => e.Sn)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("sn");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.Time)
                .HasColumnType("datetime")
                .HasColumnName("time");
        });

        modelBuilder.Entity<Tempimport>(entity =>
        {
            entity.HasKey(e => new { e.Employee, e.Dt, e.Times, e.Comid }).HasName("PK_HRM@TempImport");

            entity.ToTable("TEMPIMPORT");

            entity.Property(e => e.Employee)
                .HasMaxLength(30)
                .IsUnicode(false)
                .UseCollation("Thai_BIN");
            entity.Property(e => e.Dt)
                .HasColumnType("datetime")
                .HasColumnName("dt");
            entity.Property(e => e.Times)
                .HasMaxLength(30)
                .IsUnicode(false)
                .UseCollation("Thai_BIN");
            entity.Property(e => e.Comid)
                .HasMaxLength(30)
                .IsUnicode(false)
                .UseCollation("Thai_BIN")
                .HasColumnName("COMID");
            entity.Property(e => e.CreateBy).HasMaxLength(30);
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.DocumentNo).HasMaxLength(200);
            entity.Property(e => e.Io)
                .HasMaxLength(30)
                .IsUnicode(false)
                .UseCollation("Thai_BIN")
                .HasColumnName("IO");
            entity.Property(e => e.ModifyBy).HasMaxLength(30);
            entity.Property(e => e.ModifyDate).HasColumnType("datetime");
            entity.Property(e => e.OverDay).HasDefaultValue(false);
            entity.Property(e => e.Shift)
                .HasMaxLength(30)
                .IsUnicode(false)
                .UseCollation("Thai_BIN");
            entity.Property(e => e.SourceType).HasMaxLength(200);
            entity.Property(e => e.Status).HasMaxLength(200);
            entity.Property(e => e.Terminal)
                .HasMaxLength(30)
                .IsUnicode(false)
                .UseCollation("Thai_BIN");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}