// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BiosoftPlusFaceScanAPI.Models;

public partial class EmployeeScanTimeView
{
    public string Code { get; set; }

    public string Employee3 { get; set; }

    public string Employee2 { get; set; }

    public string Name1 { get; set; }

    public string Name2 { get; set; }

    public string Lastname1 { get; set; }

    public string Lastname2 { get; set; }

    public string TitleEng { get; set; }

    public string TitleThai { get; set; }

    public string Comid { get; set; }
}