// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BiosoftPlusFaceScanAPI.Models;

public partial class Facescanregister
{
    public int Id { get; set; }

    public string Sn { get; set; }

    public DateTime? Time { get; set; }

    public bool? Live { get; set; }

    public string Status { get; set; }

    public string Mac { get; set; }

    public string Floors { get; set; }

    public string Modelname { get; set; }
}