// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BiosoftPlusFaceScanAPI.Models;

public partial class TempContext : DbContext
{
    public TempContext(DbContextOptions<TempContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Facescanregister> Facescanregisters { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Facescanregister>(entity =>
        {
            entity.ToTable("FACESCANREGISTER");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Floors)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("floors");
            entity.Property(e => e.Live).HasColumnName("live");
            entity.Property(e => e.Mac)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("mac");
            entity.Property(e => e.Modelname)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("modelname");
            entity.Property(e => e.Sn)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("sn");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.Time)
                .HasColumnType("datetime")
                .HasColumnName("time");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}